Hash for link
mozilla/srihash.org pull request #458
Opened 2020-08-28 08:53 UTC by kota-yata

#457 

Here is the test website => https://kota-yata.github.io/srihash-gh/

2020-09-02 07:59 UTC, mozfreddyb requested changes
Looks really solid, thank you!
Please remove .DS_Store from this commit (you may also add it to .gitignore, if you wish).
But let's finish reviewing this after #453 is done.

2020-09-02 07:59 UTC, mozfreddyb commented on app.js
> +function parseContentType(res) {
nit: The function should get the header value as a string, you should do the "res.headers.get()" in the caller of this function.

2020-09-02 07:59 UTC, mozfreddyb commented on app.js
> +  const scriptEl = `<span style="color: #ffa07a">&lt;script src=</span><span style="color:#abe338">&quot;${encodeURI(
I think it's generally better to generate both result HTML strings within the if/else below. No need to create both and then just use one.

2020-09-02 07:59 UTC, mozfreddyb commented on app.js
> +      const contentType = parseContentType(response);
As above, pass resonse.headers.get("content-type") and deal with undefined/empty in the function itself.

2020-09-02 07:59 UTC, mozfreddyb commented on app.js
> +  const type = res.headers.get("content-type").split(";");
What if the passed type is undefined? Please add an early-return for error cases that returns "script"

2020-12-01 00:43 UTC, kota-yata commented
Ready to land :)

2020-12-03 09:16 UTC, merged