Add a hash function <select> choice with responsive UI
mozilla/srihash.org pull request #497
Opened 2021-05-07 13:25 UTC by kota-yata

Stealing from #462

2021-05-10 11:04 UTC, mozfreddyb approved these changes
looks good. can you publish this on your github pages for previewing?

2021-05-10 11:04 UTC, mozfreddyb commented on app.js
> +    default: throw new Error(`invalid hashing algorithm: ${hashAlgorithm}`);
I think it would be great to default to sha384 for invalid inputs.

2021-05-10 11:05 UTC, mozfreddyb commented
oh and please fix the lint violations :-)

2021-05-10 12:34 UTC, kota-yata commented
Here's preview page -> https://kota-yata.github.io/srihash.org/

I removed "engine" field from package.json since it caused the lint violations

2021-05-14 00:59 UTC, kota-yata commented
@mozfreddyb

2021-05-17 14:04 UTC, mozfreddyb requested changes
Looks good, but pls undo the downgrade of stylelint-config-standard.

2021-05-17 14:04 UTC, mozfreddyb commented on package.json
> +    "stylelint-config-standard": "^21.0.0"
Why are you switching from stylelint 22 back to stylelint 21 here?

2021-05-18 13:13 UTC, mozfreddyb approved these changes

2021-05-18 13:13 UTC, merged

2021-05-18 13:13 UTC, mozfreddyb commented
thank you @kota-yata!